name: Publish Debian Package

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or SHA to build'
        type: string
        default: 'main'

      architectures:
        type: choice
        options:
          - '["amd64"]'
          - '["arm64"]'
          - '["amd64","arm64"]'
        default: '["amd64"]'

permissions:
  contents: write
  packages: write # Optional, but good if you use GHCR

jobs:
  build-custom:
    runs-on: ubuntu-latest
    container:
      # this is what we build for: SID
      image: ghcr.io/${{ github.repository_owner }}/debian-builder:main
      # for now the image is not public ... mmc: why?
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Is this ORG-scope token? but why? others cannot READ the docker image?
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          # mmc: full.
          # todo: up to previous tag
          fetch-depth: 0 # Get all history for tagging

      - name: build
        run: |
          mkdir ../artifacts
          ./ci/mmc-build.sh


# fixme: I need a version string!
  notify:
    needs: [build-custom]
    uses: michal-maruska/workflows/.github/workflows/notify-apt-repo.yml@main
    with:
      # component: ${{ github.repository }}
      # run_id: ${{ github.run_id }}
      release: 1 # fixme
    secrets: inherit
