name: Publish Debian Package

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or SHA to build'
        type: string
        default: 'main'

      architectures:
        type: choice
        options:
          - '["amd64"]'
          - '["arm64"]'
          - '["amd64","arm64"]'
        default: '["amd64"]'

permissions:
  contents: write
  packages: write # Optional, but good if you use GHCR

jobs:
  build-custom:
    runs-on: ubuntu-latest
    container:
      # this is what we build for: SID
      image: ghcr.io/${{ github.repository_owner }}/debian-builder:main
      # for now the image is not public ... mmc: why?
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Is this ORG-scope token? but why? others cannot READ the docker image?
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          # mmc: full.
          # todo: up to previous tag
          fetch-depth: 0 # Get all history for tagging
          submodules: "recursive"

      - name: fix ownership
        # mess with permissions/ownership: actions/checkout works outside the container
        run: |
          chown -R builder:builder .

      - name: build
        run: |
          apt update
          # mkdir _artifacts
          ./ci/mmc-build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debs-amd64
          path: ${{ github.workspace }}/artifacts/*

  setup-artifacts:
    needs: [build-custom ]   # build-amd64-and-indep, build-arm64]
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    outputs:
      artifact_names: ${{ steps.compute.outputs.artifact_names }}
    steps:
      - id: compute
        run: |
          names='[debs-amd64]'
          echo "artifact_names=$names" >> $GITHUB_OUTPUT
          # fixme:  install jg
          # always include indep if it was built
          # if [ "${{ needs.build-amd64-and-indep.result }}" = "success" ]; then
          #   names=$(echo $names | jq '. + ["debs-indep"]')
          # fi
          # if [ "${{ needs.build-amd64-and-indep.result }}" = "success" ] && \
          #    [ "${{ contains(fromJson(inputs.architectures), 'amd64') }}" = "true" ]; then
          #   names=$(echo $names | jq '. + ["debs-amd64"]')
          # fi
          # if [ "${{ needs.build-arm64.result }}" = "success" ]; then
          #   names=$(echo $names | jq '. + ["debs-arm64"]')
          # fi
          # echo "artifact_names=$names" >> $GITHUB_OUTPUT

  release:
    needs: build-custom
    uses: michal-maruska/workflows/.github/workflows/debian-release.yml@main
    with:
      artifact_names: ["debs-indep", "debs-amd64"]
        # ${{ needs.setup-artifacts.outputs.artifact_names }}
      release: "1"
        # ${{ needs.update-changelog.outputs.version }}
    secrets: inherit



# fixme: I need a version string!
  notify:
    needs: [build-custom]
    uses: michal-maruska/workflows/.github/workflows/notify-apt-repo.yml@main
    with:
      # component: ${{ github.repository }}
      # run_id: ${{ github.run_id }}
      release: 1 # fixme
    secrets: inherit
